name: Rust Sweeper

on: [push]

jobs:
  test_Ubuntu:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install_dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev libsdl2-ttf-dev
      - name: Build
        run: |
          rustc --version
          cargo build
      - name: Test
        run: cargo test

  test_Windows:
    runs-on: windows-2016

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test